var contentData = [
    {
        id              : 0
        ,"title"     : "Alzheimer's Disease"
        , "image"   : "alzheimers.jpg"
        , "leadin"  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis ornare sem. Integer non ante pretium, " +
    "posuere purus nec, sodales tortor. Donec est est, suscipit eget ultricies eget, dapibus eget."
        , "content" : "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas faucibus purus libero, non condimentum lorem gravida vitae. Cras in libero consequat, commodo nisl at, pulvinar magna. Suspendisse at sodales erat, in condimentum libero. Sed lorem ante, scelerisque ac tincidunt in, suscipit et leo. Duis et est malesuada, congue diam quis, vestibulum sem. In hac habitasse platea dictumst. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam in tellus vel dolor fermentum aliquam sit amet eget ligula. In ornare lacus urna, in semper ante euismod ac. In sit amet tempus ligula. Nunc nec aliquet turpis. Praesent vel pulvinar libero. Morbi varius ullamcorper lacinia. Praesent porta, erat vitae hendrerit placerat, diam magna semper libero, nec hendrerit elit eros in diam. Suspendisse accumsan sed nunc a iaculis. Morbi at sagittis dolor.</p>"
                    +"<p>Pellentesque ac malesuada orci. Duis ultricies nisl in massa laoreet, at accumsan urna auctor. Suspendisse pulvinar vestibulum eros sed blandit. Cras finibus ornare lacus et bibendum. Nullam suscipit, arcu nec congue molestie, urna ligula sagittis lorem, ac semper augue orci ac nulla. Nam ullamcorper sit amet quam et consequat. Praesent ut aliquam lacus.</p>"
                    +"<p>Proin nec sapien a augue molestie egestas vel quis arcu. Ut vitae laoreet neque. Etiam massa dolor, venenatis finibus ligula id, dictum finibus neque. Nunc aliquam mauris dolor, eget volutpat nulla tristique sed. Integer eros ipsum, molestie quis felis eu, congue venenatis ante. Etiam ultrices facilisis consectetur. Curabitur tincidunt ligula vitae rhoncus molestie. Nullam mattis posuere elit at scelerisque. Pellentesque tempor, tortor ac consequat molestie, sapien sem egestas sapien, et elementum mi sem a erat. In hac habitasse platea dictumst.</p>"
                    +"<p>Praesent rhoncus rhoncus massa sed aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent maximus metus in nisi accumsan dictum. Quisque ac sodales dui. In pharetra luctus metus ac eleifend. Vivamus posuere sem dui, eu iaculis enim dictum sit amet. Ut ac ante vitae libero pulvinar rutrum. Aliquam mollis metus odio. Duis nec nibh mauris. Sed molestie sem eget velit vestibulum, et bibendum nunc vestibulum.</p>"
        , "twitter" : "teamalzheimers"
        , "facebook": "AlzheimersTeam"
        , "survey"  : ""
    }
    ,{
        id              : 1
        ,"title"     : "Familial Amyloid Polyneuropathy (FAP)"
        , "image"     : "amyloidosis.jpg"
        , "leadin"    : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus gravida lacus ac dui tincidunt posuere. Morbi non ipsum ac nibh dignissim faucibus eu non purus. Phasellus purus sapien, condimentum vel."
        , "content"   : "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean placerat volutpat ante a volutpat. Maecenas ut velit consectetur, porttitor quam a, condimentum eros. Etiam quis mauris suscipit lacus sagittis pretium. Praesent commodo mauris id rutrum luctus. Vivamus dignissim tortor vel nisl facilisis porttitor. Cras mattis neque dictum justo viverra auctor. Aliquam dignissim vel tellus ac varius.</p>"
                    +"<p>Donec neque erat, suscipit in arcu sed, vulputate tempus dui. Nullam tincidunt nunc libero. Donec fermentum, arcu sit amet pellentesque auctor, purus est lobortis ipsum, in elementum ipsum nisi vel enim. Cras at ante a metus molestie volutpat eget eu tortor. Aliquam tristique pharetra justo quis vehicula. Curabitur ac suscipit risus. Suspendisse sollicitudin interdum eros. Sed eros augue, blandit sit amet enim at, volutpat aliquam lectus. Suspendisse interdum gravida magna, vel malesuada enim pretium non. Proin iaculis ipsum eleifend, porta eros at, blandit libero. Vestibulum posuere nisl a nisi iaculis pulvinar. Aenean finibus sem purus, accumsan efficitur nulla condimentum et.</p>"
                    +"<p>Maecenas quis rutrum ante. Vivamus molestie leo id ultricies vulputate. Sed laoreet magna id ex laoreet eleifend. Duis rutrum pharetra justo ac sodales. Morbi quis ante eget quam ultrices bibendum. Integer ut ex tincidunt, facilisis nisi vel, laoreet quam. Maecenas dui nunc, fermentum quis risus ac, volutpat feugiat lorem. In vel magna luctus, eleifend neque ac, placerat magna.</p>"
                    +"<p>Morbi urna leo, sodales id arcu sed, rutrum dictum mi. Fusce consectetur sodales quam ut condimentum. Praesent hendrerit lectus metus, in ultrices nisi congue pharetra. Maecenas eu libero porttitor, vehicula orci vitae, consectetur massa. Nam non placerat metus. Fusce elementum posuere lacus sed molestie. Proin scelerisque, nibh ut imperdiet tincidunt, mauris nulla sodales purus, ac fermentum dui mauris ut leo. Donec nibh elit, consectetur et arcu at, hendrerit luctus lacus. Fusce accumsan elementum justo. Nam molestie vitae magna nec elementum. Ut lacus orci, dictum sed hendrerit at, consectetur ac enim. Pellentesque placerat consequat ligula, a ullamcorper lorem lacinia vitae. Proin sed malesuada nisl, vel tempus massa. Mauris condimentum gravida ipsum sollicitudin dapibus. Vestibulum gravida sapien ex, sit amet lacinia mi interdum sit amet.</p>"
        , "twitter"   : ""
        , "facebook"  : "Amyloidosis-Research-TTR-FAP-Team%2F1440623746251298?fref=ts"
        , "survey"    : ""
    }
    ,{
        id              : 2
        ,"title"     : "Meniere's Disease"
        , "image"     : "menieres.jpg"
        , "leadin"    : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc posuere risus et nisi pellentesque, at sagittis purus pharetra. Mauris eu facilisis tortor. Morbi congue ullamcorper dui, id commodo enim mollis."
        , "content"   : "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur dictum aliquam enim, ac tincidunt ante. Donec fermentum libero sit amet risus placerat pharetra. Phasellus pretium est quis arcu sollicitudin auctor. Aliquam imperdiet risus velit, eget pulvinar elit eleifend in. Pellentesque luctus lectus in placerat rhoncus. Proin ac tempor magna. Aenean commodo placerat suscipit. Etiam risus leo, imperdiet vel tellus non, ultricies scelerisque justo. Etiam eget blandit quam, sed tincidunt orci. Vestibulum accumsan lacus ipsum. Donec non mi dui. Curabitur tempus est et odio lobortis, ac interdum magna euismod. Integer feugiat, nisl at consectetur ultricies, libero enim porta est, non porta est tortor ac turpis. Donec eget dapibus eros, sit amet varius lectus.</p>"
                    +"<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam nec scelerisque ante, a placerat ex. Praesent dui tellus, tincidunt in placerat sit amet, rutrum ac lacus. Curabitur mi nibh, pharetra sed ligula ac, molestie consectetur orci. Sed dolor lorem, pretium vitae neque et, ullamcorper egestas arcu. Duis commodo egestas ipsum cursus sollicitudin. Suspendisse consequat neque nec turpis vulputate varius. Suspendisse quis odio tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec vestibulum dui sed sapien tincidunt, eu viverra dui rhoncus. Ut malesuada neque in lectus interdum, a porta ex luctus.</p>"
                    +"<p>Cras diam nulla, dapibus id purus ac, molestie consequat mauris. Cras cursus tincidunt est id eleifend. Donec tincidunt posuere ex et dictum. Proin molestie cursus neque, id porttitor nisi. Nullam malesuada purus est, at tempor dolor egestas sit amet. Sed nec imperdiet felis. Aenean magna libero, venenatis non ipsum a, sodales efficitur felis.</p>"
                    +"<p>Sed euismod, odio tempus finibus pharetra, lectus turpis porta libero, et tincidunt lectus orci eu urna. Morbi mattis sagittis dui vel porttitor. Cras nisl velit, tempor vitae sapien eu, suscipit sollicitudin tellus. Donec feugiat euismod mi nec convallis. Maecenas sed elit ac odio efficitur posuere. Nulla facilisi. Nullam maximus suscipit eros porttitor tincidunt. Nam tristique ligula et metus consequat, aliquam sollicitudin nisl placerat. Ut ut lobortis nulla, sed vehicula tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec velit vitae mauris mollis finibus. Curabitur tempus ullamcorper felis nec faucibus.</p>"
        , "twitter"   : ""
        , "facebook"  : "menieresdisease?fref=ts"
        , "survey"    : ""
    }
    ,{
        id              : 3
        ,"title"     : "Prurigo Nodularis"
        , "image"     : "prurigo.png"
        , "leadin"    : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tempus elit vitae metus blandit ornare. Morbi viverra venenatis dui molestie hendrerit. Vivamus sit amet arcu gravida, vestibulum massa vulputate, porta."
        , "content"   : "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla posuere fermentum imperdiet. Phasellus sed accumsan turpis. Curabitur ac accumsan velit. In hac habitasse platea dictumst. Mauris at mattis tortor. Donec a tincidunt ex. Integer pharetra erat in lorem auctor imperdiet. Sed ornare at erat eget pellentesque. Integer lacus eros, dapibus nec mauris sed, aliquam ultricies lacus. Sed tempus ligula purus, vitae dapibus lorem faucibus malesuada. Morbi viverra, neque sit amet interdum tempus, turpis felis posuere nisl, ac commodo ante libero quis odio. In a semper lorem. Proin tempor sem egestas augue interdum posuere. Sed rhoncus libero in purus laoreet ultrices. Suspendisse consectetur viverra sapien, nec hendrerit leo pulvinar vitae.</p>"
                    +"<p>Ut non est sit amet mi sodales consectetur id at dui. Fusce quis lorem lectus. Vivamus eget interdum libero. In porta suscipit facilisis. Aenean fringilla vestibulum enim, at blandit sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In condimentum odio pretium ipsum molestie lobortis.</p>"
                    +"<p>Vivamus iaculis, magna sit amet dignissim egestas, mi magna mollis nunc, in tristique ex est non leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut rhoncus, orci nec cursus venenatis, urna enim imperdiet massa, vitae condimentum dui felis quis velit. Aenean suscipit justo id euismod aliquam. Praesent faucibus nunc nec ante dapibus condimentum sed commodo lorem. Phasellus eu venenatis metus. Morbi scelerisque imperdiet nulla vitae rhoncus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas ut nunc metus.</p>"
                    +"<p>Nullam eu molestie est. Vivamus molestie at tortor quis ultricies. Aenean vel dolor nunc. Vestibulum tempor nunc non sapien sollicitudin, ac rutrum odio sollicitudin. Aliquam vel ex lobortis, feugiat ipsum lacinia, pharetra ipsum. Sed dignissim dapibus urna a facilisis. Mauris id finibus lectus. Nullam sagittis, urna quis vehicula euismod, ante ligula gravida est, in sagittis ipsum nisi id ante. Ut bibendum bibendum mauris vitae dapibus. Suspendisse potenti. Phasellus dapibus malesuada rutrum. Donec eu commodo enim, quis elementum lacus.</p>"
        , "twitter"   : "chronicitchteam"
        , "facebook"  : "Chronicitch?fref=ts"
        , "survey"    : ""
    }
];